### PR TITLE
Remove println! macros

### PR DESCRIPTION
**Pull request by dbxnr**
I'm using your crate as part of a CLI app and these macros are an unwanted side-effect, can they be removed?

### CODE REVIEW

**Comment by dbxnr** [comment]
Is this repo still being maintained?

**Comment by ckw017** [comment]
@marimeireles Are you still interested in maintaining the crate? If not I think I'll specify that this repo is no longer being actively maintained.

**Comment by marimeireles** [comment]
@ckw017 I can give it a try!
@dbxnr I think removing them completely might be too much. They could be useful to other people, but I'm not sure. What's your take on it?
Maybe we could introduce different logging levels. :)

**Comment by ckw017** [comment]
I don't think those prints where particularly important, so this PR is fine. @marimeireles you can merge this and then update the crate when you have the time : )

**Comment by marimeireles** [comment]
K then, thanks =)!

**Pull request merged**
